// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4GXYppGSXkdU2lAbSS5cuqqh21KCtWsc',
    appId: '1:137707352143:android:83a1efe50913f3a9bbba3a',
    messagingSenderId: '137707352143',
    projectId: 'hedyety-ff4c2',
    databaseURL: 'https://hedyety-ff4c2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hedyety-ff4c2.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCey7Z4AN5b6xrJvqMRUxfMeFNB_F8wGZk',
    appId: '1:137707352143:web:0c906f8db0881ef2bbba3a',
    messagingSenderId: '137707352143',
    projectId: 'hedyety-ff4c2',
    authDomain: 'hedyety-ff4c2.firebaseapp.com',
    databaseURL: 'https://hedyety-ff4c2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hedyety-ff4c2.firebasestorage.app',
  );

}